import CtaBanner from "@/components/CtaBanner/CtaBanner";
import DiscountSection from "@/components/discountSection/DiscountSection";
import Hero from "@/components/hero/Hero";
import IntroItems from "@/components/introItems/IntroItems";
import NewProducts from "@/components/newProducts/NewProducts";
import Head from "next/head";
import Header from "../components/header/header";

export default function Home() {
  return (
    <>
      <Head>
        <title>GymLand Apparel</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className="">
        <Hero />
        <IntroItems />
        <NewProducts />
        <DiscountSection />
        <CtaBanner />
      </main>
    </>
  );
}
