import CtaBanner from "@/components/ctaBanner/CtaBanner";
import DiscountSection from "@/components/discountSection/DiscountSection";
import Footer from "@/components/footer/footer";
import Hero from "@/components/hero/Hero";
import IntroItems from "@/components/introItems/IntroItems";
import NewProducts from "@/components/newProducts/NewProducts";
import Head from "next/head";
import { useState } from "react";
import Header from "../components/header/header";

export default function Home() {
  const [cart, setCart] = useState([]);

  const handleCartUpdate = (newItem) => {
    setCart((prevCart) => [...prevCart, newItem]);
  };
  return (
    <>
      <Head>
        <title>GymLand Apparel</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header cartCount={cart.length} />
      <main className="">
        <Hero />
        <IntroItems handleCartUpdate={handleCartUpdate} />
        <NewProducts />
        <DiscountSection />
        <CtaBanner />
      </main>
      <Footer />
    </>
  );
}
